Repository visionmedia/debug, pull requests merged in 2018-06, with the labels that each got.

#476 Drop usage of `chrome.storage` (or make the storage backend pluggable)
  src/browser.js
Labels: bug

#577 Improve usability of Windows notes w/ examples for prompts & npm script
  README.md
Labels: awaiting-response, change-patch

#579 Adding TVMLKit support
  src/browser.js
Labels: change-patch, feature
